fixed metadata bug
CuriBio/pulse3d pull request #135
Opened 2023-03-23 19:44 UTC by NikitaPoly

2023-03-23 20:04 UTC, tannermpeterson commented
What bug is this fixing?

2023-03-23 20:11 UTC, NikitaPoly commented
> What bug is this fixing?

This bug is from new files that Eric tried using on the dash board. Originally he sent me one file and I added support for them. This bug was present when Eric tried to run a different optical file, ones he had not sent to me previously. They failed during pulse3d analysis so this is the fix for those files. I ran all three files and was able to get an output xlsx.

2023-03-23 20:18 UTC, tannermpeterson requested changes

2023-03-23 20:18 UTC, tannermpeterson commented on CHANGELOG.rst
> +- Fixed missing wells when reading metadata for optical files.
This should say something more along the lines of not trying to grab metadata from wells that aren't present when loading from optical files

2023-03-24 19:44 UTC, tannermpeterson approved these changes

2023-03-24 19:44 UTC, tannermpeterson commented on tests/xlsx/test_excel_writer.py
> +@pytest.mark.parametrize(
👍

2023-03-24 21:21 UTC, merged